language: ruby
sudo: required
dist: xenial
services:
  - docker
rvm:
  - 2.4.2
before_install:
  - echo "before_install"
install:
  - echo "install"
  - gem install bundler --no-rdoc --no-ri
  - bundle install
before_script:
  - echo 'before_script'
  #- export AWS_REGION=$(docker run --env AWS_DEFAULT_REGION=us-east-2 --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} garland/aws-cli-docker aws ec2 describe-regions --query 'Regions[].{Name:RegionName}' --output text | shuf | head -n1)
  #- export TF_VAR_region=${AWS_REGION}
  #- echo "using AWS_REGION=${AWS_REGION}"
  #- export TF_WARN_OUTPUT_ERRORS=1
  - curl --silent --output terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  - sha256sum terraform.zip  | grep "6b8ce67647a59b2a3f70199c304abca0ddec0e49fd060944c26f666298e23418"
  - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v
  - curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.4.2/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
script:
  - echo 'script'
  - terraform init --input=false
  - terraform fmt -check=true
  - terraform validate # -var "region=${AWS_REGION}" 
  - docker run --rm -v $(pwd):/app/ --workdir=/app/ -t wata727/tflint --error-with-issues
  #- cd examples/some_tests
  #- terraform init
  #- terraform fmt -check=true
  #- terraform validate
  #- cd -
  - terraform -v
  - tflint
#notifications:
